### ISSUE TITLE
Warns 'Hydrogen is outdated' while it's up-to-date

### ISSUE THREAD

**Issue by SteadyStudio** [Synthetic-Dev/Hydrogen#5]
For some reason it warns 'Hydrogen is outdated!
Get the latest version by going to Plugins > Manage Plugins > Click "Update" button under "Hydrogen"
OR
Get the latest release from the github page (https://github.com/Synthetic-Dev/Hydrogen/releases)!' while the plugin is up-to-date.

![image](https://user-images.githubusercontent.com/87199833/140608705-7f1bbf85-7740-49d0-9074-b14166a0f103.png)

I've tried relaunching studio but it always warns that.
![image](https://user-images.githubusercontent.com/87199833/140608735-25815d4b-71b7-4fd5-a90f-35f882c8e41e.png)

**Comment by Synthetic-Dev** [comment]
Apologies! I never got round to publishing the latest version of the plugin after Roblox came back online from the outage! Will publish the update now.
